[build.environment]
DART_SASS_VERSION = "1.97.1"
GO_VERSION = "1.25.5"
HUGO_VERSION = "0.153.2"
NODE_VERSION = "24.12.0"
TZ = "Europe/Oslo"

[build]
publish = "public"
command = """\
  git config core.quotepath false && \
  hugo --gc --minify --baseURL "${URL}"
  """

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-store"
    Referrer-Policy = "same-origin"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Credentials = "true"
